pipeline {
    agent any

    stages {
       stage('Setup'){
            steps{
                bat "npm ci"
            }
        }
        stage('Home') {
            steps {
               // git url: 'https://github.com/lecosta10/fc-TestesFront'
                git credentialsId: 'Github_Login', url: 'https://github.com/lecosta10/fc-TestesFront'
                bat 'npm run cypress:home-test'
            }
        }
        stage('Meus endereços') {
            steps {
                git credentialsId: 'Github_Login', url: 'https://github.com/lecosta10/fc-TestesFront'
                bat 'npm run cypress:my_addresses-test'
            }
        }
        stage('Meus pedidos') {
            steps {
                git credentialsId: 'Github_Login', url: 'https://github.com/lecosta10/fc-TestesFront'
                bat 'npm run cypress:My_requests-test'
            }
        }
        
    }
}